ingest_capture:
  # Set this to the path of a completed run directory containing
  # run.json, steps.jsonl.gz, episodes.jsonl.gz (e.g., results/demo/run-20251106-120000)
  run_dir: results/demo/<run_id>
  # Root output directory where the dataset hierarchy will be written as
  # data/captures/<experiment>/<run_id>
  out_dir: data/captures
