repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--config=src/backend/pyproject.toml, --force-exclude]
      - id: ruff-format
        args: [--config=src/backend/pyproject.toml, --force-exclude]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        stages: [manual]
        pass_filenames: false
        args:
          [
            --strict,
            --config-file=src/backend/mypy.ini,
            --follow-imports=skip,
            -p,
            plume_nav_sim.registration,
          ]
        additional_dependencies:
          - types-requests
          - types-setuptools
