movie:
  # Registry id for curated datasets (data zoo); set auto_download=true to fetch when missing
  dataset_id: null
  auto_download: false
  cache_root: null  # override data_zoo cache (defaults to ~/.cache/plume_nav_sim/data_zoo)
  # Path to Zarr dataset containing concentration: (t,y,x); overrides dataset_id when set
  path: null
  # Optional overrides when attrs omitted or to force policies
  fps: null
  pixel_to_grid: null  # [scale_y, scale_x]
  origin: null         # [y0, x0] in grid units
  extent: null         # [height, width] in grid units
  step_policy: wrap    # wrap|clamp
