name: Examples and README smoke tests

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  examples-smoke:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package with dev extras
        run: python -m pip install -e "src/backend[dev]"

      - name: Registration sanity (gym.make)
        run: |
          python - <<'PY'
          import gymnasium as gym
          import plume_nav_sim as pns
          from plume_nav_sim.registration import ensure_registered
          ensure_registered()
          env = gym.make("PlumeNav-Sim-v0", action_type="oriented")
          obs, info = env.reset(seed=0)
          env.close()
          PY

      - name: README quickstart snippet
        run: |
          python - <<'PY'
          import plume_nav_sim as pns
          env = pns.make_env()
          obs, info = env.reset(seed=42)
          assert isinstance(info.get("agent_xy"), tuple)
          env.close()
          PY

      - name: Run examples (quickstart)
        working-directory: src/backend
        run: timeout 120s python -m examples.quickstart

      - name: Run examples (custom_configuration)
        working-directory: src/backend
        run: timeout 120s python -m examples.custom_configuration

      - name: Run examples (custom_components)
        working-directory: src/backend
        run: timeout 180s python -m examples.custom_components

      - name: Run examples (reproducibility)
        working-directory: src/backend
        run: timeout 120s python -m examples.reproducibility
