name: Lint and Type Check

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package with dev extras
        run: python -m pip install -e "src/backend[dev]"

      - name: flake8 (library)
        run: >-
          flake8 src/backend/plume_nav_sim
          --max-line-length=88
          --extend-ignore=E203,W503,E501
          --select=E,W,F,C,N
          --max-complexity=10
          --per-file-ignores="src/backend/plume_nav_sim/__init__.py:F401,F403,F405,src/backend/plume_nav_sim/envs/base_env.py:C901,src/backend/plume_nav_sim/core/episode_manager.py:C901"

      - name: mypy (library, strict)
        run: mypy --strict --config-file src/backend/mypy.ini src/backend/plume_nav_sim
